# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
#  servlet:
#    context-path: /homepage
spring:
  servlet:
    multipart:
      max-file-size: 100000MB
      max-request-size: 100000MB
      enabled: true
  freemarker:
    suffix: .ftl
    request-context-attribute: request
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://140.143.241.208:3307/homepage?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 4545fgjfg&*_)
      driverClassName: com.mysql.cj.jdbc.Driver


#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.db.homepage.module.*.entity
  #    typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
