# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    # 工作线程的最大数量
    max-threads: 100
    # 工作线程的最小数量
    min-spare-threads: 3
  port: 8080
#  servlet:
#    context-path: /homepage
spring:
  servlet:
    # 文件上传大小限制
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix: .ftl
    request-context-attribute: request
    cache: false
  # 环境
  profiles:
    active: dev

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.db.homepage.module.*.entity
  #    typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0

