spring:
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://140.143.241.208:3306/homepage?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver


logging:
  path: /logs